name: Build and push Docker image 

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_USERNAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build  \
             -t Test .

    - name: Tag Docker image
      run: |
        docker tag Test ${{ secrets.ACR_USERNAME }}.azurecr.io/Test:latest

    - name: Push Docker image to Azure Container Registry
      run: |
        docker push ${{ secrets.ACR_USERNAME }}.azurecr.io/Test:latest 
